host = "0.0.0.0"
port = 8080

# Path to store local storage
local_storage = "_data/guest_local_storage"

# Allow CORS from these origins
cors_origins = [
    "https://spaceoperator.com",
    "https://www.spaceoperator.com",
    "http://localhost:3000",
]

[supabase]
# Visit API Key page to see project_id and anon_key
project_id = ""
anon_key = ""
endpoint = "https://base.spaceoperator.com"

[db]
upstream_url = "https://dev-api.spaceoperator.com"
api_keys = [
    # Create an API key for your user and paste it here
    ""
]
