[package]
name = "flow-tracing"
version = "0.1.0"
edition = "2024"

[dependencies]
ahash = "0.8.12"
chrono = "0.4.41"
flow.workspace = true
flow-lib.workspace = true
tracing = "0.1.41"
tracing-log = "0.2.0"
tracing-subscriber = "0.3.19"
