[package]
name = "integration-tests"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
cargo_metadata = "0.19.1"
clap = { version = "4.5.27", features = ["derive"] }
dotenv = "0.15.0"
xshell = "0.2.7"
