//! Build script for cmds-bun.
//!
//! Scans `node-definitions/` for `.jsonc` + `.ts` pairs and auto-generates
//! `inventory::submit!()` registrations. Drop a new pair into any subdirectory
//! and it will be compiled into the binary — no Rust code changes needed.

use flow_lib::config::{CommandType, node::parse_definition};
use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};

/// Scan `defs_dir` for `.jsonc` files and pair with `.ts` files at the same
/// relative path under `src_dir`.
fn find_node_pairs(defs_dir: &Path, src_dir: &Path) -> Vec<(PathBuf, PathBuf)> {
    let mut pairs = Vec::new();
    visit_dir(defs_dir, defs_dir, src_dir, &mut pairs);
    pairs.sort_by(|a, b| a.0.cmp(&b.0));
    pairs
}

fn visit_dir(base: &Path, dir: &Path, src_dir: &Path, pairs: &mut Vec<(PathBuf, PathBuf)>) {
    let Ok(entries) = fs::read_dir(dir) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            visit_dir(base, &path, src_dir, pairs);
        } else if path.extension().is_some_and(|e| e == "jsonc") {
            // Build matching .ts path under src_dir with same relative subdir
            let rel = path.strip_prefix(base).unwrap();
            let ts_path = src_dir.join(rel).with_extension("ts");
            if ts_path.exists() {
                pairs.push((path, ts_path));
            }
        }
    }
}

fn parse_registration(jsonc_path: &Path) -> (CommandType, String) {
    let content = fs::read_to_string(jsonc_path)
        .unwrap_or_else(|error| panic!("read {}: {error}", jsonc_path.display()));
    let definition = parse_definition(&content)
        .unwrap_or_else(|error| panic!("parse {}: {error}", jsonc_path.display()));
    (definition.r#type, definition.data.node_id)
}

fn command_type_expr(ty: &CommandType) -> &'static str {
    match ty {
        CommandType::Native => "flow_lib::CommandType::Native",
        CommandType::Mock => "flow_lib::CommandType::Mock",
        CommandType::Wasm => "flow_lib::CommandType::Wasm",
        CommandType::Deno => "flow_lib::CommandType::Deno",
        CommandType::Bun => "flow_lib::CommandType::Bun",
    }
}

fn main() {
    let manifest_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let node_defs_dir = manifest_dir.join("node-definitions");
    let src_dir = manifest_dir.join("src");
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").unwrap());
    let gen_path = out_dir.join("bun_nodes_generated.rs");

    // Re-run if definitions or source files change
    println!("cargo::rerun-if-changed={}", node_defs_dir.display());
    println!("cargo::rerun-if-changed={}", src_dir.display());

    let pairs = find_node_pairs(&node_defs_dir, &src_dir);

    let mut f = fs::File::create(&gen_path).expect("create generated file");

    writeln!(f, "// Auto-generated by build.rs — do not edit").unwrap();
    writeln!(f, "// Found {} node definition pairs", pairs.len()).unwrap();
    writeln!(f).unwrap();

    for (jsonc_path, ts_path) in &pairs {
        let (command_type, scoped_name) = parse_registration(jsonc_path);
        let jsonc_abs = jsonc_path.display();
        let ts_abs = ts_path.display();
        let command_type_expr = command_type_expr(&command_type);

        writeln!(
            f,
            r#"flow_lib::submit!(flow_lib::command::CommandDescription {{"#
        )
        .unwrap();
        writeln!(f, r#"    matcher: flow_lib::command::MatchCommand {{"#).unwrap();
        writeln!(f, r#"        r#type: {command_type_expr},"#).unwrap();
        writeln!(
            f,
            r#"        name: flow_lib::command::MatchName::Exact(std::borrow::Cow::Borrowed("{scoped_name}")),"#
        ).unwrap();
        writeln!(f, r#"    }},"#).unwrap();
        writeln!(
            f,
            r#"    fn_new: futures::future::Either::Right(|nd| crate::make_compiled_bun("#
        )
        .unwrap();
        writeln!(f, r#"        include_str!("{jsonc_abs}"),"#).unwrap();
        writeln!(f, r#"        include_str!("{ts_abs}"),"#).unwrap();
        writeln!(f, r#"        nd,"#).unwrap();
        writeln!(f, r#"    )),"#).unwrap();
        writeln!(f, r#"}});"#).unwrap();
        writeln!(f).unwrap();
    }
}
