const scriptDir = new URL(".", import.meta.url);
const packageRoot = new URL("../", scriptDir);
const repoRoot = new URL("../../", packageRoot);
const specPath = new URL("schema/flow-server.openapi.json", repoRoot);
const outputPath = new URL(
  "../contracts/src/generated/flow_server_openapi.ts",
  packageRoot,
);

const jsonValueDocAliasBlock = `export type JsonValueDoc = null | JsonValueDocNonNull;
export type JsonValueDocNonNull = string | number | boolean | JsonValueDoc[] | {
    [key: string]: JsonValueDoc;
};

`;

function patchRecursiveJsonTypes(source: string): string {
  const sourceWithAliases = source.includes("export type JsonValueDoc =")
    ? source
    : source.replace(
      "/**\n * This file was auto-generated by openapi-typescript.\n * Do not make direct changes to the file.\n */\n\n",
      `/**\n * This file was auto-generated by openapi-typescript.\n * Do not make direct changes to the file.\n */\n\n${jsonValueDocAliasBlock}`,
    );

  return sourceWithAliases
    .replace(
      '        JsonValueDoc: null | components["schemas"]["JsonValueDocNonNull"];',
      "        JsonValueDoc: JsonValueDoc;",
    )
    .replace(
      `        JsonValueDocNonNull: string | number | boolean | components["schemas"]["JsonValueDoc"][] | {
            [key: string]: components["schemas"]["JsonValueDoc"];
        };`,
      "        JsonValueDocNonNull: JsonValueDocNonNull;",
    );
}

await Deno.mkdir(new URL("../contracts/src/generated", packageRoot), {
  recursive: true,
});

const command = new Deno.Command(Deno.execPath(), {
  cwd: packageRoot,
  args: [
    "run",
    "-A",
    "npm:openapi-typescript",
    specPath.pathname,
    "-o",
    outputPath.pathname,
  ],
  stdout: "inherit",
  stderr: "inherit",
});

const output = await command.output();
if (output.code !== 0) {
  throw new Error(`openapi-typescript failed with exit code ${output.code}`);
}

const generatedSource = await Deno.readTextFile(outputPath);
const patchedSource = patchRecursiveJsonTypes(generatedSource);

if (patchedSource !== generatedSource) {
  await Deno.writeTextFile(outputPath, patchedSource);
}
