[package]
name = "x402-gateway"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.6"
tokio = { version = "1.48.0", features = ["full"] }
url = "2.5.7"
x402-axum = "0.5.0"
x402-rs = "0.9.0"
