name: Rust

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

jobs:
  unit-test:
    if: ${{ ! contains(github.event.pull_request.labels.*.name, 'no-test') }}
    name: Unit test
    runs-on: self-hosted
    steps:
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: default
          override: true
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - uses: Swatinem/rust-cache@v2
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --quiet --tests --
            -D clippy::dbg_macro
            -D clippy::print_stdout
            -D clippy::print_stderr
            -A clippy::too_many_arguments
      - name: Assert Cargo.lock unchanged
        run: .github/assert_cargo_lock_unchanged.bash
      - name: Install wasm32-wasi
        run: rustup target add wasm32-wasi
      - name: Install deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Build WASM
        run: ./scripts/build_wasm_tests.bash
      - name: Build tests
        run: cargo test --quiet --no-run
      - name: Run tests
        env:
          SOLANA_DEVNET_URL: ${{ secrets.SOLANA_DEVNET_URL }}
        run: cargo test -- --skip need_key_
