name: Docker - main branch

on:
  push:
    branches:
      - "main"

jobs:
  build:
    name: Build docker image
    runs-on: [self-hosted, rust-builder]
    env:
      BRANCH: ${{ github.head_ref || github.ref_name }}
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: ./scripts/build_images.bash
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-west-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: ECR Push
        run: ./scripts/ecr-private-push.bash login
      - name: Clean up
        run: podman image prune -f

  deploy:
    name: Deploy to EKS
    needs: build
    runs-on: [self-hosted, rust-builder]
    env:
      ECR: 311141552572.dkr.ecr.us-west-2.amazonaws.com
      COMMIT: ${{ github.sha }}
    steps:
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-west-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name app-cluster-v2 --region us-west-2
      - name: Deploy pinned commit images
        run: |
          kubectl set image statefulset/flow-server flow-server=$ECR/flow-server:$COMMIT
          kubectl set image statefulset/deno-server deno-server=$ECR/cmds-server:$COMMIT init=$ECR/cmds-server:$COMMIT
          kubectl set image deployment/schema-server schema-server=$ECR/schema-server:$COMMIT

          kubectl rollout status statefulset/flow-server --timeout=10m
          kubectl rollout status statefulset/deno-server --timeout=10m
          kubectl rollout status deployment/schema-server --timeout=10m

  integration-test:
    name: Integration Test
    needs: deploy
    runs-on: [self-hosted, rust-builder]
    env:
      APIKEY: ${{ secrets.INTEGRATION_TESTS_APIKEY }}
      KEYPAIR: ${{ secrets.INTEGRATION_TESTS_KEYPAIR }}
      USDC_KEYPAIR: ${{ secrets.USDC_KEYPAIR }}
      SOLANA_DEVNET_URL: ${{ secrets.SOLANA_DEVNET_URL }}
    steps:
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: default
          override: true
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - name: Install deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - name: Build Integration Tests
        run: cargo build --bin integration-tests --quiet
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-west-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Run Integration Tests
        env:
          APIKEY: ${{ secrets.INTEGRATION_TESTS_APIKEY }}
          KEYPAIR: ${{ secrets.INTEGRATION_TESTS_KEYPAIR }}
        run: cargo run --bin integration-tests --quiet
