name: Typescript

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit-test:
    name: Type checking
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Install deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - name: Check libraries
        run: bash -c 'deno check -r @space-operator/*/src/mod.ts'
      - name: Check all
        run: bash -c 'deno check -r @space-operator/**/*.ts'
